// IPC channel names shared between main and preload, so both sides stay in sync.

export const IPC_CHANNELS = {
  core: {
    getPreferences: 'core:getPreferences',
    setPreference: 'core:setPreference',
    saveExportFile: 'core:saveExportFile',
    listSnapshots: 'core:listSnapshots',
    getSnapshot: 'core:getSnapshot',
    saveSnapshot: 'core:saveSnapshot',
    deleteSnapshot: 'core:deleteSnapshot',
    clearSnapshots: 'core:clearSnapshots',
    getNotes: 'core:getNotes',
    saveNotes: 'core:saveNotes',
  },
  lol: {
    connectionStatus: 'lol:connectionStatus',
    connectionStatusChanged: 'lol:connectionStatusChanged',
    accountSummary: 'lol:accountSummary',
    rankedSummary: 'lol:rankedSummary',
    championMasteries: 'lol:championMasteries',
    masteryCrestUrl: 'lol:masteryCrestUrl',
    ownedSkins: 'lol:ownedSkins',
    rarityGemUrl: 'lol:rarityGemUrl',
    ownedChromas: 'lol:ownedChromas',
    ownedWardSkins: 'lol:ownedWardSkins',
    ownedEmotes: 'lol:ownedEmotes',
    ownedProfileIcons: 'lol:ownedProfileIcons',
    profileIconUrl: 'lol:profileIconUrl',
    levelBorderUrl: 'lol:levelBorderUrl',
    wallet: 'lol:wallet',
    rankedEmblemUrl: 'lol:rankedEmblemUrl',
    riotPointsIconUrl: 'lol:riotPointsIconUrl',
    blueEssenceIconUrl: 'lol:blueEssenceIconUrl',
    masteryBannerUrl: 'lol:masteryBannerUrl',
    honorBadgeUrl: 'lol:honorBadgeUrl',
    playerLoot: 'lol:playerLoot',
  },
} as const;
